services:
  postgres-prisma:
    image: postgres:15
    container_name: postgres_prisma
    restart: always
    ports:
      - "9999:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: sandbox_prisma_db
    volumes:
      - test-prisma-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sandbox_redis
    restart: always
    ports:
      - "6229:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: sandbox_rabbitmq
    hostname: sandbox-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookiewww"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "ft"
    expose:
      - "8999"
    ports:
      - "8999:5672"
      - "15777:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  test-prisma-data:
  test-typeorm-data:
  redis-data:
  rabbitmq-data:
